# Final Report

## Introduction

Have you ever considered opening a business in **Riyadh, Saudi Arabia**? I bet most of you did and you spent a lot of time thinking about the best location for your business. Well, think no more, with this application, all you have to do is to specify what type of business you are interested in investing in, and it will tell you what neighborhood is best for you. Isn't that great =D

## Method and data

I got a data of all the neighborhoods in Riyadh, and I am planning to iterate on these data get the venues and build a dataframe with all neighborhoods and their top venues. Then based on category of business selected the application will find the neighborhood that is least crowded of that category to suggest it.

## Data obtained so far

In [3]:
import pandas as pd
df = pd.read_excel('Neighboorhood_Riyadh.xlsx', sheet_name='Sheet1')
df

              Neighborhood   Latitude  Longtitude
0   Al Uraija Al Gharbiyah  24.594900   46.589152
1              Al Aziziyah  24.585913   46.738071
2                Umm Salim  24.633751   46.694103
3               Al Izdihar  24.780655   46.700005
4               Al Badi'ah  24.616217   46.672458
5                At Taawun  24.773076   46.681970
6               Al Jazirah  24.664702   46.778970
7               Al Khuzama  24.715071   46.582610
8           As Sulimaniyah  24.698527   46.667436
9               As Suwaidi  24.590827   46.661607
10              As Sahafah  24.796546   46.602523
11                Al Olaya  24.692317   46.648480
12                Al Falah  24.797057   46.691701
13             Al Mursalat  24.748866   46.672379
14                Al Muruj  24.757186   46.644419
15               Al Masani  24.552304   46.708993
16               Al Maseef  24.765526   46.664032
17             Al Maizilah  24.791617   46.802808
18            Al Mughrizat  24.764036   46.708234
19                Al Malaz  24.664293   46.717901
20               King Fahd  24.740652   46.652852
21             King Faisal  24.761770   46.757147
22               An Nuzhah  24.756436   46.690350
23     An Nasim Ash Sharqi  24.738971   46.809932
24      An Nasim Al Gharbi  24.725718   46.788947
25                An Nazim  24.861030   46.819576
26                Al Wahah  24.741184   46.705654
27                 Al Wadi  24.789519   46.673773
28                Al Wurud  24.724320   46.660952
29                  Shubra  24.574491   46.647010
30              Salahuddin  24.732847   46.679460
31                  Tuwaiq  24.575686   46.506156
32      Dhahrat Al Badi'ah  24.597210   46.633130
33               Ghirnatah  24.795889   46.735990
34                Manfuhah  24.599439   46.710986
35               Ar Rayyan  24.711396   46.760452
36               Ar Rabwah  24.693773   46.736934